

import React, { useState } from "react";
import {
  Wallet,
  PieChart,
  FileText,
  Gift,
  ThumbsUp,
  Users,
  Zap,
  ChevronDown,
} from "lucide-react";
import { NavBar } from "./NavBar";
import Footer from "./Footer";
import { useNavigate } from "react-router-dom";

// --- Data Structure for Services ---
const servicesData = [
  {
    id: "wealth",
    icon: Wallet,
    title: "Wealth Management",
    summary: "Tailored strategies for growing, protecting, and transferring your wealth efficiently.",
    details: [
      {
        term: "Fixed Deposit",
        desc: "Play it safe, with our highest returns. Go tension free, make Fixed Deposit @12-18% per annum.",
      },
      {
        term: "Grow With Us",
        desc: "Invest your money with No Loss assurance and grow with us getting the share of returns generated by the company.",
      },
      {
        term: "Risk Management",
        desc: "Protect your assets with insurance and risk mitigation strategies.",
      },
      {
        term: "Legacy Planning",
        desc: "Create a lasting legacy through effective estate planning and charitable giving.",
      },
    ],
  },
  {
    id: "portfolio",
    icon: PieChart,
    title: "Portfolio Management",
    summary: "Dynamic investment strategies tailored to your personal risk tolerance and financial goals.",
    details: [
      {
        term: "Customized Investment Strategies",
        desc: "We design personalized investment plans to meet your risk tolerance and financial objectives.",
      },
      {
        term: "Diversification",
        desc: "Our approach minimizes risk by spreading investments across various asset classes.",
      },
      {
        term: "Regular Reviews",
        desc: "We continuously monitor and adjust your portfolio to ensure optimal performance.",
      },
    ],
  },
  {
    id: "planning",
    icon: FileText,
    title: "Financial Planning",
    summary: "Building a robust financial roadmap for your future, including retirement and estate planning.",
    details: [
      {
        term: "Comprehensive Analysis",
        desc: "We assess your current financial situation and future goals.",
      },
      {
        term: "Retirement Planning",
        desc: "Secure a comfortable retirement with our strategic saving and investment solutions.",
      },
      {
        term: "Estate Planning",
        desc: "Ensure your assets are distributed according to your wishes.",
      },
    ],
  },
];

const benefitsData = [
  {
    id: "extras",
    icon: Gift,
    title: "Additional Benefits for Investors",
    summary: "Exclusive perks and incentives designed to add extra value to your partnership with us.",
    details: [
      {
        term: "Premium Subscriptions",
        desc: "If you invest ₹30k+, Netflix, Prime Video, and Hotstar Premium ID will be given for free.",
      },
      {
        term: "Credit Card Access",
        desc: "We provide Credit Cards of all major banks to avail maximum discounts while shopping online.",
      },
      {
        term: "Demat Account Earnings",
        desc: "If you are not using your Demat account (Groww, Zerodha...), give it to us for 1 year and earn ₹1000.",
      },
      {
        term: "IPO Partnership",
        desc: "Apply IPOs together with us and get profit share in ratio of investment.",
      },
    ],
  },
  {
    id: "whyus",
    icon: ThumbsUp,
    title: "Why Choose Berry AMC?",
    summary: "Our commitment to expertise, personalized service, and unwavering integrity sets us apart.",
    details: [
      {
        term: "Expertise & Experience",
        desc: "Our team of seasoned financial advisors and portfolio managers brings decades of experience to the table.",
      },
      {
        term: "Personalized Service",
        desc: "We take the time to understand your unique financial situation and provide tailored solutions.",
      },
      {
        term: "Transparency & Integrity",
        desc: "Clear communication and utmost integrity in all decisions.",
      },
      {
        term: "Innovative Solutions",
        desc: "Leveraging latest tech and insights to keep you ahead in the financial landscape.",
      },
    ],
  },
];




const ServiceCard = ({ icon: Icon, title, summary, details }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const toggleExpand = () => setIsExpanded(!isExpanded);

  return (
    <div
      className={`bg-white rounded-2xl p-6 md:p-8 shadow-xl border border-gray-100 cursor-pointer transition duration-300
      ${isExpanded ? 'ring-4 ring-blue-200 shadow-2xl scale-[1.02]' : 'hover:shadow-lg hover:border-blue-300'}
      `}
      onClick={toggleExpand}
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-blue-100 rounded-full">
            <Icon className="w-6 h-6 text-blue-600" />
          </div>
          <h2 className="text-xl md:text-2xl font-bold text-gray-800">{title}</h2>
        </div>
        <ChevronDown
          className={`w-6 h-6 text-blue-600 transition-transform duration-300 ${isExpanded ? 'rotate-180' : 'rotate-0'
            }`}
        />
      </div>

      <p className="mt-4 text-gray-600 mb-4">{summary}</p>

      {/* Interactive Details Section */}
      <div
        className={`overflow-hidden transition-all duration-500 ease-in-out ${isExpanded ? 'max-h-[500px] opacity-100 pt-4' : 'max-h-0 opacity-0'
          }`}
      >
        <div className="border-t border-gray-200 mt-4 pt-4">
          <h3 className="text-lg font-semibold text-blue-600 mb-3">Key Benefits:</h3>
          {/* <ul className="space-y-4 text-gray-700 text-sm">
            {details.map((item, index) => (
              <li key={index} className="flex items-start">
                <span className="text-blue-500 mr-2 min-w-[1.2rem] flex-shrink-0">&bull;</span>
                <div>
                  <strong className="text-gray-800">{item.term}:</strong> {item.desc}
                </div>
              </li>
            ))}
          </ul> */}
          <ul className="space-y-4 text-gray-700 text-sm">
            {details.map((item, index) => {
              const [showFDDetails, setShowFDDetails] = useState(false);

              if (item.term === "Fixed Deposit") {
                return (
                  <li key={index} className="flex flex-col">
                    <div className="flex items-start">
                      {/* Bullet and FD Text aligned properly */}
                      <span className="text-blue-500 mr-2 mt-1 flex-shrink-0">&bull;</span>
                      <div className="flex-1">
                        <p className="inline">
                          <strong className="text-gray-800">{item.term}:</strong>{" "}
                          {item.desc}
                        </p>
                        {/* Inline More Details */}
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            setShowFDDetails(!showFDDetails);
                          }}
                          className="ml-2 text-blue-600 text-sm font-medium underline hover:text-blue-800 transition cursor-pointer"
                        >
                          {showFDDetails ? "Hide Details" : "More Details"}
                        </button>
                      </div>
                    </div>

                    {/* Animated FD Details Section */}
                    <div
                      className={`overflow-hidden transition-all duration-500 ease-in-out ${showFDDetails ? "max-h-60 opacity-100 mt-3" : "max-h-0 opacity-0"
                        }`}
                    >
                      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-gray-800">
                        <ul className="space-y-1">
                          <li>• 0–6 months — <strong>12%</strong></li>
                          <li>• 6–9 months — <strong>14%</strong></li>
                          <li>• 9–12 months — <strong>16%</strong></li>
                          <li>• Above 12 months — <strong>18%</strong></li>
                        </ul>
                        <p className="mt-2 text-sm text-blue-700 font-semibold">
                          Interest is compounded yearly.
                        </p>
                      </div>
                    </div>
                  </li>
                );
              }

              // Default rendering for other items
              return (
                <li key={index} className="flex items-start">
                  <span className="text-blue-500 mr-2 mt-1 flex-shrink-0">&bull;</span>
                  <div>
                    <strong className="text-gray-800">{item.term}:</strong> {item.desc}
                  </div>
                </li>
              );
            })}
          </ul>




        </div>
      </div>
      <p className="mt-4 text-sm text-blue-500 font-medium">{isExpanded ? 'Click to collapse' : 'Click for more details'}</p>
    </div>
  );
};

// --- Main App Component ---
export const Services = () => {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-gray-50 font-sans ">
      <NavBar />

      {/* Hero Section */}
      <div className="bg-blue-700 pt-38 text-white pb-20 px-4 md:px-12 text-center rounded-b-3xl shadow-2xl  ">
        <h1 className="text-4xl sm:text-5xl font-extrabold mb-4 tracking-tight">
          Comprehensive Financial Services
        </h1>
        <p className="max-w-3xl mx-auto text-xl opacity-90 font-light">
          Unlock your financial potential with Berry AMC's innovative and personalized
          wealth management, portfolio strategies, and planning solutions.
        </p>
      </div>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 mb-5">
        {/* Core Services Section */}
        <section className="mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-800 text-center mb-10">Our Core Financial Solutions</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {servicesData.map((service) => (
              <ServiceCard key={service.id} {...service} />
            ))}
          </div>
        </section>

        {/* Benefits Section */}
        <section className="mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-800 text-center mb-10 mt-20">Value-Added Partner Benefits</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {benefitsData.map((benefit) => (
              <ServiceCard key={benefit.id} {...benefit} />
            ))}
          </div>
        </section>

        {/* Call to Action */}
        <div className="bg-blue-600 text-white text-center py-12 px-6 rounded-xl shadow-lg mt-20">
          <h2 className="text-3xl font-bold mb-3">
            Ready to Build Your Financial Future?
          </h2>
          <p className="mb-6 max-w-2xl mx-auto opacity-90 text-lg">
            Schedule a free consultation today to see how our expertise can align with your aspirations.
          </p>
          <button className="bg-white text-blue-600 px-8 py-3 rounded-full font-bold text-lg shadow-md hover:bg-gray-100 hover:shadow-xl transition transform hover:scale-[1.02] duration-300 cursor-pointer" onClick={() => navigate("/client/registration")}>
            Secure Your Future Today
          </button>
        </div>
      </main>
      <Footer />
    </div>
  );
};

